export const MANUFACTURING_STATUS = {
  DRAFT: "DRAFT",
  IN_PROGRESS: "IN_PROGRESS",
  QC: "QC",
  DONE: "DONE",
  CANCELLED: "CANCELLED",
};

export const STATUS_TABS = ["ALL", MANUFACTURING_STATUS.DRAFT, MANUFACTURING_STATUS.IN_PROGRESS, MANUFACTURING_STATUS.QC, MANUFACTURING_STATUS.DONE];
